version: "3"

services:
    ttrss:
        image: x86dev/docker-ttrss
        container_name: ttrss
        restart: always
        environment:
            - SELF_URL_PATH=https://rss.ionathan.ch/
            - TTRSS_SELF_URL=https://rss.ionathan.ch/
            - TTRSS_PROTO=https
            - TTRSS_URL=rss.ionathan.ch
            - DB_PORT_5432_TCP_ADDR=ttrssdb
            - DB_PORT_5432_TCP_PORT=5432
            - DB_HOST=ttrssdb
            - DB_PORT=5432
            - DB_TYPE=pgsql
        ports:
            - "8080:8080"
        depends_on:
            - ttrssdb
    ttrssdb:
        image: postgres:alpine
        container_name: ttrssdb
        restart: always
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
        expose:
            - "5432"
        volumes:
            - ttrssdb:/var/lib/postgresql/data
volumes:
    ttrssdb:
