version: "3"

services:
    mediawiki:
        image: mediawiki
        container_name: mediawiki
        restart: always
        ports:
            - "8282:80"
        volumes:
            - data:/var/www
            - ./LocalSettings.php:/var/www/html/LocalSettings.php

volumes:
    data:
