version: '2'

services:
  app:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - 8080:80
    volumes:
      - ./data:/var/www/html/data
      - ./config:/var/www/html/config
      - ./themes:/var/www/html/themes
      - ./apps:/var/www/html/custom_apps
    restart: always
