version: '2'

services:
  app:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: next.ionathan.ch
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    restart: always
