version: '2'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
  app:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: next.ionathan.ch
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
