version: "3"

services:
    ttrss:
        image: valvin1/docker-ttrss # use x86dev/docker-ttrss once #36 is merged into master
        container_name: ttrss
        restart: always
        environment:
            - SELF_URL_PATH=http://ress.ert.space/
            - TTRSS_SELF_URL=http://ress.ert.space/
            - TTRSSL_URL=ress.ert.space
            - DB_PORT_5432_TCP_ADDR=ttrssdb
            - DB_PORT_5432_TCP_PORT=5432
            - DB_HOST=ttrssdb
            - DB_PORT=5432
            - DB_TYPE=pgsql
        ports:
            - "8181:8080"
        depends_on:
            - ttrssdb
    ttrssdb:
        image: nornagon/postgres
        container_name: ttrssdb
        restart: always
        expose:
            - "5432"
        volumes:
            - ttrssdb:/var/lib/postgresql/9.3/main
volumes:
    ttrssdb:
