version: "3"

services:
    syncthing:
        image: syncthing/syncthing
        container_name: syncthing
        restart: always
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - "8384:8384"
            - "22000:22000"
            - "21027:21027/udp"
        volumes:
            - .:/var/syncthing
