version: "3"

services:
  funkwhale:
    image: funkwhale/all-in-one:0.19.0
    container_name: funkwhale
    restart: unless-stopped
    env_file: .env
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
      - /srv/docker/funkwhale/data:/data
      - /srv/docker/funkwhale/data/music:/music
    ports:
      - 5000:80

